server:
  port: ${SERVER_PORT}


spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        ddl-auto: none
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}  
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
            
app:
  auth:
    tokenSecret: 
    tokenExpirationMsec: 

    
awsProperties:
  endpointUrl: ${AWS_ENDPOINT}
  bucketName: ${AWS_BUCKET_NAME}
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}